version: 2
 
sources:
  - name: public
    description: This is a replica of the Snowflake database used by our app
    database: RETAIL_DB
    tables:
      - name: Customer
      - name: Product
      - name: Transaction
      - name: Stock